# Generated by Django 6.1 on 2026-08-13 14:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='subscriptionplan',
            name='max_columns',
            field=models.PositiveIntegerField(default=30),
        ),
    ]
