# Generated by Django 6.1 on 2026-08-14 15:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_subscriptionplan_max_columns'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='blogpost',
            name='category',
        ),
        migrations.RemoveField(
            model_name='blogpost',
            name='featured_image',
        ),
    ]
